-- --------------------------------------------------------
-- This file is part of Shopbay.org (http://shopbay.org)
-- For the full copyright and license information, please view the LICENSE
-- file that was distributed with this source code. 
--;
-- --------------------------------------------------------
--
-- For 'Rights' module
--;
INSERT INTO `s_auth_item` VALUES('Customer Payment', 1, 'Customer Payment', NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Customer.Index', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Customer.View', 0, NULL, NULL, 'N;');

INSERT INTO `s_auth_item` VALUES('Merchant Payment', 1, 'Merchant Payment', NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.Index', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.View', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.Create', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.Update', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.Delete', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.Activate', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Management.Deactivate', 0, NULL, NULL, 'N;');

INSERT INTO `s_auth_item` VALUES('Merchant Account Payment', 1, 'Merchant Account Payment', NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Merchant.Index', 0, NULL, NULL, 'N;');
INSERT INTO `s_auth_item` VALUES('Payments.Merchant.View', 0, NULL, NULL, 'N;');

--
-- Customer role has access to Payment module;
INSERT INTO `s_auth_itemchild` VALUES('Customer', 'Customer Payment');
INSERT INTO `s_auth_itemchild` VALUES('Customer Payment', 'Payments.Customer.Index');
INSERT INTO `s_auth_itemchild` VALUES('Customer Payment', 'Payments.Customer.View');
-- Merchant role has access to Payment module - shop payment method management;
INSERT INTO `s_auth_itemchild` VALUES('Merchant', 'Merchant Payment');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.Index');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.View');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.Create');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.Update');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.Delete');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.Activate');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Payment', 'Payments.Management.Deactivate');

-- Merchant role has access to Payment module - merchant account payment record;
INSERT INTO `s_auth_itemchild` VALUES('Merchant', 'Merchant Account Payment');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Account Payment', 'Payments.Merchant.Index');
INSERT INTO `s_auth_itemchild` VALUES('Merchant Account Payment', 'Payments.Merchant.View');

-- --------------------------------------------------------
--
-- Table structure for table `s_payment`
--;
DROP TABLE IF EXISTS `s_payment`;
CREATE TABLE `s_payment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` varchar(12) NOT NULL,
  `payment_no` varchar(20) NOT NULL,
  `type` tinyint(4) NOT NULL COMMENT '0=Sale, 1=Refund',
  `payment_method` varchar(1500) NOT NULL COMMENT 'schema refer to PaymentFormBehavior. This column stored json encoded payment_method in different languages. It buffers about 20 languages, assuming each takes 50 chars.',
  `currency` varchar(3) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `reference_no` varchar(20) NOT NULL COMMENT 'payment reference no, e.g. order no',
  `trace_no` varchar(500) DEFAULT NULL COMMENT 'System trace no, normally generated by external payment processor',
  `create_time` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
-- --------------------------------------------------------
--
-- Constraints for dumped tables
--;
--
-- Constraints for table `s_payment`
--;

INSERT INTO `s_payment` (`id`, `account_id`, `payment_no`, `type`, `payment_method`, `currency`, `amount`, `reference_no`, `trace_no`, `create_time`) VALUES
(-1, 0, 'DEMO_PAYMENT_NO', 0, '0', 'SGD', '24.80', 'ORDER_NO', NULL, 1409842228);

-- --------------------------------------------------------
--
-- Table structure for table `s_payment_method`
--;
DROP TABLE IF EXISTS `s_payment_method`;
CREATE TABLE IF NOT EXISTS `s_payment_method` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL DEFAULT '0' COMMENT 'account_id=0 means System Attribute. Refer to s_account',
  `shop_id` int(11) NOT NULL COMMENT 'Refer to s_shop',
  `name` varchar(1000) NOT NULL COMMENT 'This column stored json encoded name in different languages. It buffers about 20 languages, assuming each take 50 chars.',
  `method` int(1) NOT NULL COMMENT 'refer to PaymentMethod class',
  `params` varchar(5000) NOT NULL COMMENT 'method specific parameters (JSON format)',
  `status` varchar(10) NOT NULL,
  `create_time` int(10) NOT NULL,
  `update_time` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
--
-- Constraints for dumped tables
--;
--
-- Constraints for table `s_payment_method`
--;
ALTER TABLE `s_payment_method`
  ADD CONSTRAINT `s_payment_config_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `s_account` (`id`);

--
-- Demo record for table `s_payment_method`
--;
INSERT INTO `s_payment_method` (`id`, `account_id`, `shop_id`, `name`, `method`, `params`, `status`, `create_time`, `update_time`) VALUES
(-1, -1, -1, '{"zh_cn":"ATM\\/\\u73b0\\u91d1\\u5b58\\u5165","en_sg":"ATM\\/Cash Bank-in"}', 101, '{"sourceMethod":100,"mode":"101","instructions":{"zh_cn":"\\u8bf7\\u4ed8\\u6b3e\\u5230\\u4ee5\\u4e0b\\u94f6\\u884c\\u8d26\\u53f7\\u6765\\u786e\\u8ba4\\u60a8\\u7684\\u8ba2\\u5355\\uff1a\\r\\n\\r\\n\\u94f6\\u884c\\u540d\\u79f0\\uff1a<\\u60a8\\u7684\\u94f6\\u884c>\\r\\n\\u94f6\\u884c\\u6237\\u53e3\\u8d26\\u53f7: <\\u60a8\\u7684\\u94f6\\u884c\\u6237\\u53e3\\u8d26\\u53f7>\\r\\n\\u94f6\\u884c\\u6237\\u53e3\\u7528\\u6237\\u540d\\u79f0: <\\u60a8\\u7684\\u94f6\\u884c\\u6237\\u53e3\\u7528\\u6237\\u540d\\u79f0>\\r\\n\\r\\n\\u5f53\\u60a8\\u4ed8\\u597d\\u6b3e\\u4e86\\u8bf7\\u66f4\\u65b0\\u60a8\\u7684\\u8ba2\\u5355\\u81f3\\"\\u5df2\\u4ed8\\u6b3e\\"\\u3002\\u4e00\\u65e6\\u4ed8\\u6b3e\\u6838\\u5bf9\\u6210\\u529f\\uff0c\\u6211\\u4eec\\u4f1a\\u5f00\\u59cb\\u5904\\u7406\\u60a8\\u7684\\u8ba2\\u5355\\u3002","en_sg":"Please make your payment to confirm your order:\\r\\n\\r\\nBank Name: <your bank name>\\r\\nAccount Number: <your bank account number>\\r\\nAccount Name: <your bank account name>\\r\\n\\r\\nPlease update us when your payment is done by setting order to \\"Paid\\". Upon successful payment verification, we will start process your order."}}', 'PAY;ON;', 1413972304, 1413972307);
